version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_php
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_app_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: very_secure_root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - my_network

volumes:
  dbdata:

networks:
  my_network:
    driver: bridge